// <auto-generated />
using ConsoleApp.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace CoreTP1.Migrations
{
    [DbContext(typeof(passManagerContext))]
    [Migration("20171001144443_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("ConsoleApp.SQLite.Password", b =>
                {
                    b.Property<int>("PasswordId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UsernameId");

                    b.Property<string>("hashedPass");

                    b.Property<string>("tag");

                    b.HasKey("PasswordId");

                    b.ToTable("Passwords");
                });

            modelBuilder.Entity("ConsoleApp.SQLite.Username", b =>
                {
                    b.Property<int>("UsernameId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MainPassword");

                    b.Property<string>("Name");

                    b.Property<string>("Salt");

                    b.HasKey("UsernameId");

                    b.ToTable("Usernames");
                });
#pragma warning restore 612, 618
        }
    }
}
